import tensorflow as tf
from tensorflow.keras import layers, models
import numpy as np
import os
from sklearn.model_selection import train_test_split

def create_model(input_shape):
    model = models.Sequential([
        layers.Input(shape=input_shape),
        layers.Conv1D(64, 3, activation='relu'),
        layers.MaxPooling1D(2),
        layers.Conv1D(128, 3, activation='relu'),
        layers.GlobalAveragePooling1D(),
        layers.Dense(64, activation='relu'),
        layers.Dropout(0.3),
        layers.Dense(1, activation='sigmoid') # Binary: Chainsaw or Not
    ])
    
    model.compile(optimizer='adam',
                  loss='binary_crossentropy',
                  metrics=['accuracy'])
    return model

def train_and_export():
    # Placeholder for loading preprocessed data
    # In a real scenario, you'd load the .npy files generated by preprocess_audio.py
    # For now, we simulate data to show the training pipeline
    X = np.random.rand(1000, 40, 40) # 1000 samples, 40 MFCCs, 40 time steps
    y = np.random.randint(0, 2, 1000)
    
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
    
    model = create_model((40, 40))
    model.fit(X_train, y_train, epochs=10, batch_size=32, validation_data=(X_test, y_test))
    
    # Save the model
    model.save('vanrakshak_model.h5')
    
    # Convert to TFLite
    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    tflite_model = converter.convert()
    
    with open('vanrakshak_model.tflite', 'wb') as f:
        f.write(tflite_model)
    
    print("Model trained and exported to vanrakshak_model.tflite")

if __name__ == "__main__":
    train_and_export()
